### PR TITLE
Feature 03

### PR DESCRIPTION
**Pull request by eng-eng11**
### Project 1: Bubble Sort
Sorting algorithms are some of the earliest that you typically get exposed to in Computer Science. It may not be immediately obvious how important they are, but it shouldn’t be hard to think of some examples where your computer needs to sort some massive datasets during everyday operations.

### CODE REVIEW

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
Hi @falguniislam you have made good progress, however, bubble_sort_by isn't working properly at the moment, the output is wrong please look into that. :pray: 
Kindly request a review when done


**HINT**
bubble_sort_by(array) { |left, right| left.length - right.length }).to eq %w[hi hey hello]
     
       expected: ["hi", "hey", "hello"]
            got: ["hey", "hello", "hi"]

**Changes Required**

**Review by maelfosso — CHANGES_REQUESTED** [review]
Hello @falguniislam 

It's almost OK :smile: Only one bug to fix.
```ruby
irb(main):003:0> bubble_sort_by(['hey', 'hi', 'hello'])
Traceback (most recent call last):
        5: from /home/elvisfosso/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        4: from (irb):3
        3: from bubble_sort_by.rb:7:in `bubble_sort_by'
        2: from bubble_sort_by.rb:7:in `each'
        1: from bubble_sort_by.rb:8:in `block in bubble_sort_by'
LocalJumpError (no block given (yield))
irb(main):004:0> 
```
To fix it, you must raise an exception when **no block given**.

Kindly, make that change and submit a new code review request please.

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com)

**Review by maelfosso — CHANGES_REQUESTED** [review]
Hello @falguniislam ,

Please, could take this review in consideration https://github.com/falguniislam/RUBY-PROJECT-Advanced-Building-Blocks---Bubble-Sort/pull/3#pullrequestreview-303398942

Thanks

**Comment by eng-eng11** [comment]
I AM REALLY CONFUSED I FIX THE BUG BUT STIIL I DID NOT UNDERSTAND ABOUT no block given.

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Good job :+1:  @falguniislam 
As pointed out by the previous TSE, we need to check the presence of a block or we raise an exception if there isn't.
This can be done by wrapping the while loop inside an if statement.
```def bubble_sort_by(arr)```
      ``` if block_given?```
          ```while loop```
       ```else```
          ```raise 'No block given'```
       ```end```
     ```end```

#### Make those changes and re-submit for another review.
### Martin Afani

**Review by maelfosso — CHANGES_REQUESTED** [review]
Hello @falguniislam ,

There is still a problem. Please read that issue https://github.com/falguniislam/RUBY-PROJECT-Advanced-Building-Blocks---Bubble-Sort/pull/3/#pullrequestreview-303505474

Thank

**Pull request merged**
